#GD-75 AuctionTrading.Domain
IT-Siberians/AuctionTraidingMicroservice pull request #1
Opened 2024-08-20 14:09 UTC by Yana-Kryukova

2024-08-23 05:58 UTC, NikeTorchwood commented on AuctionTrading/AuctionTrading.Domain/Entities/Bid.cs
> +        public DateTime Timestamp => DateTime.Now;
могу ошибаться но разве запись  Timestamp => DateTime.Now; не говорит о том, что если мы обращаемся к этому свойству - то он выдает значение DateTime.Now? тоесть если мы даже за чтением будем обращаться он не обновляет время?(я проверил в рантайме, да здесь ошибка надо исправить)

2024-08-23 06:00 UTC, NikeTorchwood commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        public AuctionLot(Guid id, Title title, Description description,
огромнейший конструктор, подумай о том чтобы можно было бы применить паттерны проектирования, вроде фабрика помогает или что то подобное

2024-08-23 06:01 UTC, NikeTorchwood commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        private Money(long amountInKopecs) : base(new DecimalValidator(), amountInKopecs)
нет открытого конструктора

2024-08-23 06:02 UTC, NikeTorchwood commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        public static Money FromKopecs(long amountInKopecs)
обожаю все рофлы, я лично одобряю наименование Копекс)

2024-08-23 06:05 UTC, NikeTorchwood approved these changes
отличный код, доменный слой 
из того что можно улучшить
открыть конструктор в Money, подумать над тем чтобы упросить формирование Lot(хотя там возможно никак)
обязательно требую оставить Копекс)

2024-08-23 13:32 UTC, oleggolen requested changes
В целом очень хороший код, очень хорошая реализация ValueObject, работа с перегрузкой методов и операторов, кастомная иерархия иключений, реализован базовый функционал сущностей. Единственное, что надо поправить это убрать лишние методы и интерфейсы из доменной модели, а часть перенести в уровень приложения, добавить доменных исключений и объеденить их  локальные иерархии, добаить ограничения на строки, не только на null or whitespace, дореализовать или убрать нереализоанные методы, разбить иерархию исключений. Очень надеюсь, что мои замечания помогут написать хороший ООП код, убрать нереализованные методы и реализовать доменный слой "как по учебнику"

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Base/Entity.cs
> +        /// </summary>
Можно сделать просто свойством с только модификатором get

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        public AuctionLot(Guid id, Title title, Description description,
Вообще для решения проблемы огромного конструктора помогает паттерн строитель, но тут скорее всего это нормальное явление

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new ArgumentException("RepurchasePrice must be greater than startPrice.");
Создать кастомное доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new ArgumentException("EndDate must be greater than StartDate.");
Создать кастомное доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            DateTime startDate, DateTime endDate, LotStatus status, Seller seller, IEnumerable<Bid> bids)
Можно этот аргумент тоже убрать

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            throw new NotImplementedException();
Реализовать метод

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new InvalidOperationException();
Сделать кастомное доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new InvalidOperationException();
Сделать кастомное доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new InvalidOperationException();
Сделать кастомное доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        public bool IsCurrentBid(Bid newBid)
Не очень очевидное название метода, да и мне кажестя, что этот метод можно сделать приватным, так как он участвует только во внутренней логики расчётов

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            return (newBid.Amount > minAmount && newBid.Timestamp < this.EndDate) ? true : false;
Убрать лишние ключевые слова this

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Bid.cs
> +        public DateTime Timestamp => DateTime.Now;
Да, тут полностью согласен, тут лучше не использовать такую инициализацию

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Bid.cs
> +        public Bid(Customer customer, AuctionLot lot, Money amount)
Сделать primary конструктор

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Customer.cs
> +    public class Customer : Entity<Guid>, ICustomer
Для чего нужен интерфейс ICustomer для сущности? Это же не сервис

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Customer.cs
> +
Здесь лучше воспользоваться свойством, а не методом

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Customer.cs
> +        }
Здесь лучше подойдёт свойство

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Customer.cs
> +        }
Не очень понимаб смысл этого метода, скорее всего его надо убрать

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Customer.cs
> +        }
Можно сверять по Id, у лота есть явное свойство владелец, и у Customer есть свойство Id и их можно сравнить

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Customer.cs
> +                throw new InvalidOperationException();
Сделать кастомное более конкретное доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
>      {
Зачем нужен интерфейс для доменной сущности?

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +        public Seller(Guid id, Username username, IEnumerable<AuctionLot> auctionLots)
Это можно убрать из конструктора

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +            : base(id)
Сделать primary конструктор

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +                throw new InvalidOperationException(ExceptionMessage.CANNOT_CANCEL_LOT_ANOTHER_SELLER);
Сделать кастомное более подходящее доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +                throw new InvalidOperationException(ExceptionMessage.CANNOT_CANCEL_NOT_ACTIVE_LOT);
Сделать кастомное более подходящее доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +                throw new InvalidOperationException(ExceptionMessage.CANNOT_CANCEL_LOT_EMPTY_SEQUENCE);
Сделать кастомное более подходящее доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +        }
Заменить на свойство

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +        }
Заменить на свойство

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +                throw new InvalidOperationException(ExceptionMessage.CANNOT_GET_LOT_ANOTHER_SELLER);
Сделать кастомное более подходящее доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +            if (auctionLot == null)
Сделать кастомное более подходящее доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +                throw new InvalidOperationException(ExceptionMessage.CANNOT_GET_NOT_ACTIVE_LOT);
Сделать кастомное более подходящее доменное исключение

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Entities/Visitor.cs
>      }
Мне кажется класс не должен иметь таких методов, можно прото сделать сервис на уровне Application для получения этого всего, даже оставив этот интерфейс

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Interfaces/ICustomer.cs
> +    }
Нет смысла в этом интерфейсе

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Interfaces/ISeller.cs
>      }
Нет смысла в этом интерфейсе

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.Domain/Interfaces/IVisitor.cs
> +    }
Перенести на слой бизнес-логики и назвать по-другому

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        }
Заменить просто на автосвойства

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        public int CompareTo(Money other)
Проверить на null

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        public bool Equals(Money x, Money y)
Проверить на null

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        }
Достаточно просто перегрузок операторов

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        }
Добавить проверки на null и на корректность типов

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        }
И добавить проверку на равенство ссылок

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +            return (int)(AmountInKopecs ^ (AmountInKopecs >> 32));
Почему не воспользоваться стандартной библиотекой?

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        }
Зачем дополнительный метод?

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +    public class Money : ValueObject<decimal>, IEqualityComparer<Money>, IComparable<Money>
Нужен интерфейс IEuitable

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Validation/StringValidator.cs
> +        }
Мне кажется нужна проверка не только на null но ещё и на ограничения по длине строки, можно добавить сюда или сделать отдельные валидаторы

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Base/IValidator.cs
> +    public interface IValidator<T>
Добаить ограничение на примитивный тип, а также пометить модификатором in

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +    public abstract class ValueObject<T> : IEquatable<ValueObject<T>>
Добавить ограничение на примитивный тип

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +        public readonly T Value;
Лучше делать тут автосвойство с только методом get

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            => Equals(other as ValueObject<T>);
Проверить на корректность типов и равенство ссылок

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Exception/ArgumentNonPositiveException.cs
> +    internal class ArgumentNonPositiveException : DomainValidationException
Я бы здесь лучше использовал FromatException

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Exception/ArgumentNullOrWhiteSpaceException.cs
> +        public ArgumentNullOrWhiteSpaceException(string? message, string? paramName)
убрать nullable

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Exception/DomainValidationException.cs
> +        public DomainValidationException(string? message, string? paramName)
убрать Nullable

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Exception/DomainValidationException.cs
> +        public DomainValidationException(string? message)
убрать nullable

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Exception/DomainValidationException.cs
> +    internal class DomainValidationException : ArgumentException
Я бы здеь придмал какое-то другое название исключения, раз он наследован от ArgumentException, потому что многие значения могут иметь значение в некорректном формате и тут же ArgumentException не подойдёт, лучше у конкретных исключений использовать системные исключения, максимально близко подходящие по смыслу, и если есть общность, то выделять в иерархие конкретные группы исключений

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Exception/ValidatorNotSpecifiedException.cs
> +        public ValidatorNotSpecifiedException(string? message, string? objectType)
Убрать nullable

2024-08-23 13:32 UTC, oleggolen commented on AuctionTrading/AuctionTrading.ValueObjects/Exception/ValidatorNotSpecifiedException.cs
> +    internal class ValidatorNotSpecifiedException : DomainValidationException
Очень странное название исключения, если честно, даже не мону понять в чём его смысл и стоит ли его вообще иметь, надо подумать

2024-08-26 15:24 UTC, m-a-ilnitsky requested changes
В целом, пока есть есть много возможностей для улучшения кода.

И лучше всегда просматривать сообщения и варнинги выдаваемые студией.
Она даёт много подсказок:
![image](https://github.com/user-attachments/assets/a5df9cc6-9a2b-446e-a5c7-5cfd2ef14422)

Также лучше после каждого изменения кода использовать автоформатирование файла (Ctrl+K, Ctrl+D).
И можно использовать форматирование солюшена, особенно перед коммитом:
![image](https://github.com/user-attachments/assets/a04e0d83-7b2a-4daf-a90d-e3f070d4896d)

И нужно обращать внимание когда студия выделяет что-то более темным или более блеклым цветом - она таким образом подсказывает когда что-то лишнее.
И если студия подчеркивает что-то то там тоже лучше смотреть варнинги и подсказки как улучшить код

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Base/Entity.cs
> +namespace AuctionTrading.Domain.Base
AuctionTrading.Domain.Base - по этому имени namespace не понятно к чему относится Base.
Здесь папка Base по идее должна быть внутри папки Entities

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Base/Entity.cs
> +        /// </summary>
Согласен

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (repurchasePrice!=null && repurchasePrice < startPrice)
Неправильно бросать одно исключение для двух таких разных ситуаций.
Будет непонятно какая из ситуаций произошла

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (repurchasePrice!=null && repurchasePrice < startPrice)
И видно что сейчас не используется автоформатирование.
Лучше всегда применять автоформатирование.
Перед каждым сохранением (Ctrl+S) выполнять форматирование (Ctrl+K, Ctrl+D)

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            Title = title;
Для всех не-nullable полей в конструкторе лучше выполнять проверку на null.
Удобнее всего делать так:
Title = title ?? throw new ArgumentNullException(nameof(title));
но с доменным исключением

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        public void ChangeStatus(LotStatus newLotStatus)
И методы и конструкторы лучше разделять пустой строкой.
Чтобы код визуально делился как-бы на абзацы

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (repurchasePrice!=null && repurchasePrice < startPrice)
Еще для автоформатирования всего солюшена можно использовать меню Analyze/Code Cleanup/Run Code Cleanup

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new InvalidOperationException();
В целом плохо бросать исключение без сообщения или какой-то другой информации (кроме случаев очень конкретных кастомных исключений, которым просто не нужно передавать дополнительную информацию).
Лучше передавать в исключение максимум информации, чтобы если оно было брошено, можно было сразу понять в чем проблема.
Это упростит отладку кода

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new ArgumentException("EndDate must be greater than StartDate.");
И в сообщении или в полях исключения лучше указать сами значения обеих дат.
Это упростит отладку

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (!this.IsActive)
Здесь и в других вызовах полей и свойств не нужно указывать this, эта практика характерна для динамически типизированных языков, типа Python и JavaScript, т.к. там иначе будет ошибка.
if (!IsActive) выглядит чище.
И сама студия выделяет такие this более тёмным цветом, чтобы показать, что там варнинг

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            bool flag = IsCurrentBid(newBid);
Перед строкой 104 лучше вставить пустую строку, чтобы визуально разбить код метода на два смысловых блока, блок валидации и блок основных действий.
Код бросающий исключение лучше всегда выделять пустыми строками, чтобы места в которых работа метода может прерваться были лучше видны в коде метода.
В целом, лучше всегда разбивать код пустыми строками на смысловые блоки

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (!this.IsActive)
Видно, что первый this темнее второго:
![image](https://github.com/user-attachments/assets/d11f25f1-1e35-4c8a-a3d6-8a84a469038a)

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                    newBid.Amount + this.FixedBid;
В таких случаях тернарный оператор лучше форматировать так:
![image](https://github.com/user-attachments/assets/75adb856-8e2a-47c3-a51f-2f8162ed46c6)

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/Bid.cs
> +        /// <summary>
Лучше после каждого свойства добавить пустую строку, чтобы свойство визуально отделялось от документации относящейся к другому свойству

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/Bid.cs
> +        public DateTime Timestamp => DateTime.Now;
Сейчас это свойство-геттер, фактически гет-метод, поэтому здесь нет инициализации, и метод всегда возвращает новое значение.
Здесь нужно вместо свойства-геттера нужно сделать автосвойство только с геттером или ридонли-поле.
Автосвойство:
public DateTime Timestamp { get; } = DateTime.Now;
Поле:
public readonly DateTime Timestamp = DateTime.Now;
Визуально похоже, на текущий вариант - возможно была опечатка.
Или задавать значение поля/свойства в конструкторе, чтобы не было возможности для такой опечатки

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/Bid.cs
> +            Amount = amount;
Нужно бросать исключения для null-значений аргументов

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/Customer.cs
> +
Согласен с Олегом, здесь как раз нужно свойство-геттер.
Но его лучше объявить выше конструктора, как обычные свойства, чтобы сразу было видно какие в сущности есть свойства и как они реализованы

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            bool flag = IsCurrentBid(newBid);
flag - неинформативное имя, лучше назвать аналогично методу из которого это значение получено:
 isCurrentBid

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/Customer.cs
> +        #endregion // Properties
Мне кажется плохая практика скрывать поля и свойства класса в регионах.
Когда открываешь файл нестатического класса, ожидаешь увидеть какие данные в нем содержатся.
А тут все данные скрыты от взора.
На мой взгляд регионы для полей и свойств имеет смысл делать только когда их очень много и они группируются по смыслу в несколько отдельных блоков
Для методов это

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/UserName.cs
> +    public class Username(string name) : ValueObject<string>(new StringValidator(), name)
Имя файла отличается от имени класса.
Возможно это эффект неразличимости регистра символов в именах файлов в Windows.
Если это так, то чтобы от этого избавиться нужно временно переименовать файл (добавить в имя произвольный набор символов), закоммитить, а потом опять поменять имя на правильное и заново закоммитить

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/Customer.cs
> +        }
Здесь вроде не получится сделать свойство, т.к. у метода есть аргумент.
Если только этот аргумент на самом деле не нужен..

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/Visitor.cs
>      }
Сущность не нужна, т.к. у нее нет состояния.
Лучше действительно сделать сервис

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Exception/ExceptionMessage.cs
> +﻿namespace AuctionTrading.Domain.Exception
Exception - по идее имя папки/namespace должно быть во множественном числе.
Но т.к. namespace не содержит исключений, лучше назвать папку Messages или Strings

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Exception/ExceptionMessage.cs
> +    internal static class ExceptionMessage
Я думаю это тот редкий случай когда классу лучше дать имя во множественном числе ExceptionMessages, т.к. класс играет роль папки для хранения набора данных

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/AuctionTrading.ValueObjects.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Сейчас по имени проекта получается, что ValueObjects не относятся к домену.
И получается что глядя на имена проектов не получается угадать имена namespace:
Например в реальности namespace в коде такой:
AuctionTrading.Domain.ValueObject.Base
А глядя на имя проекта кажется что такой:
AuctionTrading.ValueObject.Base

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Base/IValidator.cs
> +    public interface IValidator<T>
Не соглашусь, т.к. в ValueObject могут хранить, например, строки, ограничение на примитивный тип здесь не подходит

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +    public abstract class ValueObject<T> : IEquatable<ValueObject<T>>
Здесь, тоже самое, ограничение на примитивный тип не подходит и з-за необходимости хранить строки в ValueObject

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            return Value?.ToString() ?? GetType().ToString();
Если значение не должно быть равно null, по идее здесь вместо ? можно использовать !

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +        }
В обоих операторах не нужны две ветки вместо этого достаточно просто вызвать статический метод Equals, а он сам инкапсулирует в себе всю ту же самую логику.

И в отличие от Java в C# вместо Object и String (зеленого цвета) обычно пишут object и string (синего цвета).
И статический Equals можно вызывать непосредственно без указания Object. или object. перед именем метода.
Сейчас студия сама выделяет Object темным цветом, подсказывая, что его можно удалить.

И по правой кнопки мыши можно ткнуть в Object и нажать Quick Actions, студия сама предложит упростить запись

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/AuctionTrading.ValueObjects.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
AuctionTrading.Domain.ValueObject.Base - и сейчас в namespace часть ValueObject в единственном числе, должно быть множественное число

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Description.cs
> +namespace AuctionTrading.Domain.ValueObject
Не хватает множественного числа в имени папки ValueObject

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Exception/ArgumentNonPositiveException.cs
> +﻿namespace AuctionTrading.Domain.ValueObject.Exception
Не хватает множественного числа в имени папки Exception

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +            amountInRubles = Decimal.Round(amountInRub, 2);
Здесь студия тоже предлагает заменить зелёный Decimal на синий decimal

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +    public class Money : ValueObject<decimal>, IEqualityComparer<Money>, IComparable<Money>
Видимо IEquatable

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        public static Money FromKopecs(long amountInKopecs)
Я вот думаю... может нам забить на вещественные decimal, и считать деньги только в рублях, целыми числами?

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        private readonly decimal amountInRubles;
Не понимаю, почему вместо использования свойства Value используется поле amountInRubles.
Тогда нет смысла наследоваться от ValueObject

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        private readonly decimal amountInRubles;
Здесь для копеек и рублей (или только копеек) можно было сделать дополнительные свойства, но само значение хранить в Value

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        }
В текущем варианте метод можно сделать статическим.
Но действительно непонятно зачем он нужен

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        public override bool Equals(object other)
В сигнатуре должно быть object?
Студия сама намекает

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +            return (int)(AmountInKopecs ^ (AmountInKopecs >> 32));
Здесь нужно  просто взывать GetHashCode самого свойства или поля:
return amountInRubles.GetHashCode();

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        }
В таких случаях лучше использовать краткий синтаксис свойства-геттера:
public decimal AmountInRubles => amountInRubles;

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        private readonly decimal amountInRubles;
И имя приватного поля должно начинаться с символа подчеркивания

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +            get { return (int)(amountInRubles * KopecFactor); }
По смыслу должно быть приведение к long

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Validation/DecimalValidator.cs
> +namespace AuctionTrading.Domain.ValueObject.Validation
Validation - имя папки/namespace  должно отражать не действие (валидация), а хранимые объекты (валидаторы).
Поэтому должно быть имя Validators

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Validation/DecimalValidator.cs
> +    public class DecimalValidator : IValidator<decimal>
Непонятное имя валидатора.
Очевидно, что на сам тип decimal такие ограничения накладывать не нужно.
Здесь скорее всего должна идти речь не о decimal, а о Money

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Validation/DecimalValidator.cs
> +            if (value<=0)
Видно что не используется автоформатирование

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Validation/StringValidator.cs
> +            if (String.IsNullOrWhiteSpace(value))
Здесь тоже вместо зелёного))) String пишут обычно синий))) string
Типа в едином стиле с примитивными типами

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            return (newBid.Amount > minAmount && newBid.Timestamp < this.EndDate) ? true : false;
Здесь не нужен тернарный оператор.
Если его убрать результат будет тот же самый, т.к. само условие тернарного оператора возвращает bool.
Поэтому от тернарного оператора достаточно оставить только его условие

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            _validator = validator;
Можно упростить с помощью такого синтаксиса:
_validator = validator ?? throw new ValidatorNotSpecifiedException(ExceptionMessage.VALIDATOR_MUST_BE_SPECIFIED, this.GetType().FullName);

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.Domain/Entities/Seller.cs
> +                throw new InvalidOperationException(ExceptionMessage.CANNOT_CANCEL_LOT_EMPTY_SEQUENCE);
Запись можно упростить таким синтаксисом:
var auctionLot = _auctionLots.SingleOrDefault(lot) ?? throw new InvalidOperationException(ExceptionMessage.CANNOT_GET_LOT_EMPTY_SEQUENCE);

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +            return (other is Money) && Equals((Money)other);
return (other is Money) && Equals((Money)other);
Эту запись можно упростит так:
return (other is Money money) && Equals(money);

2024-08-26 15:24 UTC, m-a-ilnitsky commented on AuctionTrading/AuctionTrading.ValueObjects/Money.cs
> +        }
Там выражение (other is Money) по факту делает и то и другое

2024-08-29 17:14 UTC, closed without merging