#GD-106 EFRepository
IT-Siberians/AuctionTraidingMicroservice pull request #12
Opened 2024-10-06 13:50 UTC by Yana-Kryukova

Олег, посмотрите пожалуйста папки Domain(исправила недочеты и реализовала интерфейсы репозиториев) и папку Infrastructure. 

У меня не получается сделать миграции, что то не то с моими конфигурациями...
Ошибка по поводу AuctioLot, конструктор не позволяет добавить навигационное свойство Seller

2024-10-07 16:03 UTC, oleggolen requested changes
В целом достаточно всё хорошо, выделены слои, добавлен EF, выполнены конфигурации, но появилось чего-то очень много нового непонятного и лишнего, и я бы всё-таки делал дополнительные проверки и приведения с часовыми поясами

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Infrastructure/Repositories.Implementations/InMemory/InMemoryRepository.cs
> +        }
Лучше возвращать какой-нибудь bool, говорящий об успешном/неуспешном обновлении данных

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Infrastructure/Repositories.Implementations/InMemory/InMemoryRepository.cs
> +        }
Лучше возвращать какой-нибудь bool, говорящий об успешном/неуспешном удалении данных

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Infrastructure/Repositories.Implementations/InMemory/InMemoryAuctionLotsRepository.cs
> +            => Task.FromResult(Entities.Where(x => x.EndDate == endDateUtc));
А здесь есть приведение к времени UTC?

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfRepository.cs
> +        }
Лучше тоже возвращать какой-нибудь bool говорящий об успешном/неуспешном обнолении данных

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfRepository.cs
> +        }
Лучшще тоже возвращать какой-нибудь bool, говорящий об успешном/неуспешном удалении данных

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfRepository.cs
> +        public Task DeleteAsync(TEntity entity)
Два метода удаления связаны между собой, можно переиспользовать логику одного в другом

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfAuctionLotRepository.cs
> +            => _auctionLots.Where((x) => x.EndDate == endDateUtc);
А это время гарантировано, что записано в часовом поясе UTC?

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Infrastructure/AuctionTrading.Infrastructure.EntityFramework/Configurations/SellerConfiguration.cs
> +            builder.Navigation("_auctionLots").AutoInclude(); // Вот тут не уверена!!!
Можно и оставить, если нет циклических вызовов, как это было у меня в репозитории, у преподавателя, есть коллекция уроков, каждый из которых содержит преподавателя. Если что-то такое есть, то лучше это всё дело разрешать в репозиториях и делать Include по надобности, а если нет, то можно и так написать

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain.Repositories.Abstractions/IRepository.cs
> +        Task DeleteAsync(TId id);
Всем этим методам необходимо добавить какой-нибудь bool, чтобы можно было отслеживать успешность/неуспешность операции

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Enums/LotStatus.cs
> +        Completed = 8
Почему здесь степени двойки?

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
>              }
Можно преобразовать в выражение возвращения через switch и стрелочную функцию

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/AuctionLot/AuctionLotModel.cs
> +        public decimal? RepurchasePrice { get; }
Стоит тоже добавить init

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/AuctionLot/ViewAuctionLotDetailsModel.cs
> +    }
Не могу понять, что за класс и для чего он нужен

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/Customer/RemoveAuctionLotFromWatchListModel.cs
> +    }
Для чего нужен этот класс?

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/Customer/AddAuctionLotToWatchListModel.cs
> +    }
Зачем нужен этот класс?

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/UsernameValidator.cs
> +        public int? MIN_LENGTH => null;
Не очень мне нравится, когда ограничения nullable, когда я говорил про то, чтобы вынести общую логику через наследование, я не имел в виду навесить дефолтных значений

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/TitleValidator.cs
> +        public int? MAX_LENGTH => 50;
Не очень мне нравится, когда ограничения nullable, когда я говорил про то, чтобы вынести общую логику через наследование, я не имел в виду навесить дефолтных значений

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/DescriptionValidator.cs
> +        public int? MAX_LENGTH => null;
Не очень мне нравится, когда ограничения nullable, когда я говорил про то, чтобы вынести общую логику через наследование, я не имел в виду навесить дефолтных значений

2024-10-07 16:03 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ITextValidator.cs
> +        public int? MIN_LENGTH { get; }
Не очень мне нравится, когда ограничения nullable, когда я говорил про то, чтобы вынести общую логику через наследование, я не имел в виду навесить дефолтных значений

2024-10-08 14:58 UTC, Yana-Kryukova commented on AuctionTrading/Infrastructure/Repositories.Implementations/InMemory/InMemoryRepository.cs
> +        }
Исправила

2024-10-08 14:58 UTC, Yana-Kryukova commented on AuctionTrading/Infrastructure/Repositories.Implementations/InMemory/InMemoryRepository.cs
> +        }
исправила

2024-10-13 10:08 UTC, closed without merging