#GD-106 Fixed infrastructure layer
IT-Siberians/AuctionTraidingMicroservice pull request #14
Opened 2024-10-14 12:18 UTC by Yana-Kryukova

2024-10-14 13:51 UTC, Barmalej24 approved these changes
В целом неплохо, есть только пожелания

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Application/AuctionTrading.Application.Models/AuctionLot/AuctionLotModel.cs
> +    public class AuctionLotModel : IModel<Guid>
можно заменить на record

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Application/AuctionTrading.Application.Models/AuctionLot/CreateAuctionLotModel.cs
> +    public class CreateAuctionLotModel : ICreateModel
можно заменить на record

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Application/AuctionTrading.Application.Models/Base/BidderCreateModel.cs
> +    public abstract class BidderCreateModel : IBidderCreateModel<Guid>
record

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Application/AuctionTrading.Application.Models/Base/BidderModel.cs
> +    public abstract class BidderModel : IModel<Guid>
record

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Application/AuctionTrading.Application.Models/Bid/BidModel.cs
> +    public class BidModel : IModel<Guid>
record

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Application/AuctionTrading.Application.Models/Bid/CreateBidModel.cs
> +    public class CreateBidModel : ICreateModel
record

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Application/AuctionTrading.Application.Models/Customer/BidOnAuctionLotModel.cs
> +    public class BidOnAuctionLotModel
record

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Application/AuctionTrading.Application.Models/Seller/CancelAuctionLotModel.cs
> +    public class CancelAuctionLotModel
record

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Controllers/WeatherForecastController.cs
удалить из проекта

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Program.cs
> +            builder.Services.AddNpgsql<ApplicationDbContext>("Host=localhost;Port=5432;Database=AuctionTradingdb;UserName=postgres;Password=12345", options =>
вынести в файл настройки, сделать проверку на наличие строки

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Program.cs
> +            builder.Services.AddSwaggerGen();
добавить описательную часть

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Presentation/AuctionTrading.WebHost/WeatherForecast.cs
удалить из проекта

2024-10-14 13:51 UTC, Barmalej24 commented on AuctionTrading/Presentation/AuctionTrading.WebHost/appsettings.Development.json
> +    }
перенести строки подключения вынести сюда.

2024-10-14 19:14 UTC, m-a-ilnitsky approved these changes

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Application/AuctionTrading.Application.Models/AuctionLot/AuctionLotModel.cs
> +    public class AuctionLotModel : IModel<Guid>
Это необязательно, но реально удобнее.
Текста получится сильно меньше.
Вместо: public required Guid Id { get; init; }
Будет: Guid Id,

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Application/AuctionTrading.Application.Services/Mapping/AuctionLotMapping.cs
> +    public class AuctionLotMapping : Profile
Удобнее сделать один MappingProfile файл для всех сущностей слоя: AuctionLot, Bid, Customer, и т.д.

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                    return BidStatus.FaultedIncorrectBid;
Так конечно лучше, но вроде предлагали этот код вынести в отдельную функцию и здесь её вызывать

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Bid.cs
> +        public AuctionLot AuctionLot { get; }
Я думаю, лучше было бы саму сущность AuctionLot назвать более кратко Lot.
Т.к. здесь нет других лотов, кроме лота аукциона, то слово Auction не несёт полезной информации, оно избыточно.
И здесь все сущности относятся к аукциону, но ставка называется просто Bid, а не AuctionBid

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/AuctionTrading.Infrastructure.EntityFramework/Configurations/AuctionLotConfiguration.cs
> +            );
А эта логика конвертации дат точно нужна, если везде и так используется Utc?

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/AuctionTrading.Infrastructure.EntityFramework/Configurations/BidConfiguration.cs
> +            );
Аналогично про необходимость конвертации

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/AuctionTrading.Infrastructure.EntityFramework/Configurations/AuctionLotConfiguration.cs
> +                .HasConversion(title => title.Value, title => new Title(title))
Здесь одинаковые имена title в двух лямбдах неинформативны.
В первой лямбде можно оставить имя title, т.к. это объект типа Title, или сократить до t.
А во второй лямбде лучше дать более информативное имя, например str или s, т.к. это объект типа string

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/AuctionTrading.Infrastructure.EntityFramework/Configurations/AuctionLotConfiguration.cs
> +                .HasConversion(title => title.Value, title => new Title(title))
Аналогично в других HasConversion

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/AuctionTrading.Infrastructure.EntityFramework/Configurations/AuctionLotConfiguration.cs
> +                .HasConversion(title => title.Value, title => new Title(title))
Имена переменных лямбд должны отражать смысл переменной или её тип, тогда код лямбд будет понятнее.
Т.к. здесь смысл одинаковый, а тип разный, при именовании лучше отталкиваться от типа

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfAuctionLotRepository.cs
> +                .Include(l => l.LastBid)
Здесь LastBid не является навигационным свойством, по смыслу это метод.
Поэтому его не нужно добавлять в Include.
Но если хочется иметь возможность использовать LastBid в AuctionLot, то в Include нужно добавить _bids

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfCustomerRepository.cs
> +            .FirstOrDefaultAsync(s => s.Username.Value == username);
Здесь свойство ObservableAuctionLots нет имеет смысла добавлять в Include (а может и вообще нельзя), т.к. это не автосвойство, а фактически метод.
Вместо него в Include нужно добавить само поле _observableAuctionLots

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfRepository.cs
> +            => (await context.Set<TEntity>().ToListAsync()).AsEnumerable();
Можно не писать AsEnumerable(), т.к. приведение к базовому типу и так выполнится автоматически

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfRepository.cs
> +        : IRepository<TEntity, TId> where TEntity : Entity<TId> where TId : struct
Когда есть несколько where, лучше каждый where писать с новой строки

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfRepository.cs
> +        }
Метод CheckEntity(TEntity entity) не нужен.
Вместо него можно использовать встроенный метод:
ArgumentNullException.ThrowIfNull(entity, nameof(entity));

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfRepository.cs
> +            return Task.FromResult(true);
Вместо return Task.FromResult(true); можно использовать результат SaveChangesAsync(), как делает Юрий

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfSellerRepository.cs
> +            .FirstOrDefaultAsync(s => s.Username.Value == username);
Здесь тоже вместо геттера ActiveAuctionLots в Include нужно использовать поле

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/Repositories.Implementations/InMemory/InMemoryRepository.cs
> +        : IRepository<TEntity, TId> where TEntity : Entity<TId> where TId : struct
Когда есть несколько where, лучше каждый where писать с новой строки

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/Repositories.Implementations/InMemory/InMemoryRepository.cs
> +        }
Вместо CheckEntity можно использовать встроенный метод ArgumentNullException.ThrowIfNull

2024-10-14 19:14 UTC, m-a-ilnitsky commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Controllers/WeatherForecastController.cs
Можно пока оставить как пример, но удалить позже, после добавления своих контроллеров

2024-10-14 19:21 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfAuctionLotRepository.cs
> +                .Include(l => l.LastBid)
И лучше не использовать "эл малое" как имя, даже сейчас в тексте оно выглядит как единица, а в другом шрифте будет выглядеть как "И большое". Если в каком-то более сложном выражении использовать такое имя, то можно потом не понять что это именно "эл малое"

2024-10-15 15:10 UTC, oleggolen requested changes
Критично нарушение SOLID, а также надо проверить тот пункт, что написал МИхаил, и советую попользоваться везде новым синтаксисом, для этого можно использовать ReSharper или Rider и отрефакторить код

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Controllers/WeatherForecastController.cs
Удалить целиком

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Presentation/AuctionTrading.WebHost/WeatherForecast.cs
Да удалить целиком

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Program.cs
> +            builder.Services.AddNpgsql<ApplicationDbContext>("Host=localhost;Port=5432;Database=AuctionTradingdb;UserName=postgres;Password=12345", options =>
Согласен

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Program.cs
> +            builder.Services.AddSwaggerGen();
Согласен

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfAuctionLotRepository.cs
> +                .FirstOrDefaultAsync(l => l.Id == id);
Согласен, что лучше назвать lot

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfRepository.cs
> +        : IRepository<TEntity, TId> where TEntity : Entity<TId> where TId : struct
Добавить ограничения на то, что TId являются сравнимыми

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfRepository.cs
> +            return Task.FromResult(true);
Согласен

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/DescriptionValidator.cs
> +        public int MAX_LENGTH => 0;
Явное нарушение принципа подстановки Лисковой. Если не везде такие константы используются, то лучше их и не использовать или в какой-нибудь интерфейс вынести, но точно не так

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/DescriptionValidator.cs
> +        public int MAX_LENGTH => 0;
Поправка, тогда лучше тут было просто не реализовывать этот интерфейс, но нарушение SOLID осталось

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
>                  default:
Однозначно куда-то вынеси сложный код

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/Base/BidderModel.cs
> +    public abstract class BidderModel : IModel<Guid>
Тут согласен

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/Base/IBidderCreateModel.cs
> +    public interface IBidderCreateModel<out TId> where TId : struct
Добавить ограничение на сравниваемость типов для TId

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/Base/IModel.cs
> +    public interface IModel<out TId> where TId : struct
Добавить ограничение на сравниваемость типов TId

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Infrastructure/AuctionTrading.Infrastructure.EntityFramework/Configurations/AuctionLotConfiguration.cs
> +            );
При использовании с Postgres в докере летят исключения, если так не делать не знаю почему, но видимо это у меня было взято

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/Customer/BidOnAuctionLotModel.cs
> +    public class BidOnAuctionLotModel
Согласен

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/Seller/CancelAuctionLotModel.cs
> +    public class CancelAuctionLotModel
Согласен

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
>              }
Можно переписать в switch statement expression

2024-10-15 15:10 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
>              Bid newBid = new Bid(this, lot, amount, DateTime.UtcNow);
Воспользоваться кратким new

2024-10-18 12:14 UTC, closed without merging