#GD-236
IT-Siberians/AuctionTraidingMicroservice pull request #16
Opened 2024-10-27 12:44 UTC by Yana-Kryukova

Выкладываю для обсуждения и жду помощи!

Не работает почему-то метод получить продавца по имени и аналогичный метод получить покупателя по имени...

В доменене сделала метод SetCancel - завершить аукцион по лоту открытым, потому что в слое application я меняю статус всем лотам на завершенный по дате смотрю...

Вообще не уверена в своих CRUD операциях...

Везде добавила к ним canceledToken

В слое Presentation еще не реализовала валидацию - в процессе.

Как мне заканчивать аукцион по лотам...

Еще поняла, что у меня в БД нет двух таблиц, одна с продавец и его наблюдаемые лоты и вторая лот и его фотографии...

У меня также большие сомнения с разросшимся перечислением статус ставки BidStatus...

2024-10-28 15:09 UTC, Yana-Kryukova commented
Выкладываю для обсуждения и жду помощи!

Не работает почему-то метод получить продавца по имени и аналогичный метод получить покупателя по имени...

В доменене сделала метод SetCancel - завершить аукцион по лоту открытым, потому что в слое application я меняю статус всем лотам на завершенный по дате смотрю...

Вообще не уверена в своих CRUD операциях...

Везде добавила к ним canceledToken

В слое Presentation еще не реализовала валидацию - в процессе.

Как мне заканчивать аукцион по лотам...

Еще поняла, что у меня в БД нет двух таблиц, одна с продавец и его наблюдаемые лоты и вторая лот и его фотографии...

У меня также большие сомнения с разросшимся перечислением статус ставки BidStatus...

2024-10-28 16:16 UTC, NikeTorchwood commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfSellerRepository.cs
> +            .FirstOrDefaultAsync(s => s.Username.Equals(username), cancellationToken);
здесь

2024-10-28 16:19 UTC, NikeTorchwood commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Controllers/SellersController.cs
> +            var sellers = await sellersApplicationService.GetSellersAsync(cancellationToken);
почему данный экшн метод не тянет сущности с инклуд auctionedLots?
Просто для понимания логики

2024-10-28 16:22 UTC, NikeTorchwood commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Controllers/SellersController.cs
> +                return NotFound(username);
мне кажутся все ответы ошибок не информативными
я бы прописывал текст ошибки там где необходимо

2024-10-28 16:27 UTC, NikeTorchwood commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Controllers/AuctionLotsController.cs
> +        public async Task<IActionResult> CreateAuctionLot(CreateAuctionLotRequest request, CancellationToken cancellationToken)
здесь не совсем понятно, если у нас сервис черновика будет работать, то содержание Guid в CreateAuctionLotRequest, считаю оправданным, а так Guid через эндпоинт выглядит лишним

2024-10-28 16:28 UTC, NikeTorchwood commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Controllers/AuctionLotsController.cs
> +            return Created("", mapper.Map<AuctionLotShortResponse>(auctionLot));
можно использовать CreateAtAction, уберет пустую строку и уже проверит доступен ли данный лот

2024-10-28 16:30 UTC, NikeTorchwood commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Controllers/CustomersController.cs
> +    public class CustomersController(ICustomersApplicationService customersApplicationService,
мне кажется суффикс Application можно опустить

2024-10-28 16:30 UTC, NikeTorchwood commented on AuctionTrading/Presentation/AuctionTrading.WebHost/Controllers/CustomersController.cs
> +    public class CustomersController(ICustomersApplicationService customersApplicationService,
чисто косметический коммент

2024-10-28 16:37 UTC, NikeTorchwood commented on AuctionTrading/Domain/AuctionTrading.Domain.Repositories.Abstractions/IRepository.cs
> +    public interface IRepository<TEntity, in TId>
не понимаю почему это находится в кор слое, интерфейсы репозиториев относятся же к аппликейшн слою

2024-10-28 16:39 UTC, NikeTorchwood commented on AuctionTrading/Infrastructure/Repositories.Implementations/EF/EfCustomerRepository.cs
> +            => _customers.Include("_observableAuctionLots")
из-за этого не работает создание покупателя.
вот что думаю, посмотрел, не вижу связи или логики как определяются "наблюдаемые лоты", считаю что у тебя получится решить самостоятельно:)

2024-10-28 16:47 UTC, NikeTorchwood commented on AuctionTrading/Application/AuctionTrading.Application.Models/Seller/SellerModel.cs
> +    public record class SellerModel(Guid Id, string Username) : BidderModel(Id, Username)
слово класс студия подчеркивает как ненужное

2024-10-28 16:48 UTC, NikeTorchwood commented on AuctionTrading/Application/AuctionTrading.Application.Models/Seller/SellerModel.cs
> +    public record class SellerModel(Guid Id, string Username) : BidderModel(Id, Username)
для красивого форматирования я бы использовал
namespace AuctionTrading.Application.Models.Seller;

public record class SellerModel(Guid Id, string Username) : BidderModel(Id, Username)
{
    тело
 }

2024-10-28 16:50 UTC, NikeTorchwood commented on AuctionTrading/Application/AuctionTrading.Application.Models/AuctionLot/AuctionLotModel.cs
> +        decimal? LastBid) : IModel<Guid>;
класс содержит неиспользуемые юзинг

2024-10-28 17:00 UTC, NikeTorchwood commented on AuctionTrading/Application/AuctionTrading.Application.Services/AuctionLotsApplicationService.cs
> +                new(auctionLotInformation.StartPrice),
я бы либо явно указывал о том что за параметр, либо хотя бы использовал new Class, ооочень тяжелый сервис с точки зрения когнитивной нагрузки.

2024-10-28 17:04 UTC, NikeTorchwood commented on AuctionTrading/Application/AuctionTrading.Application.Services/AuctionLotsApplicationService.cs
> +            var res = await sellersRepository.UpdateAsync(seller, cancellationToken); // не уверена, что эта строчка нужна!
думаю не нужна.
почему не нужна:
первое дальше в методе ты не используешь seller.
по окончанию метода данная переменная будет уничтожена.
второе таблица sellers содержит связи но явно не содержит колонку с lotId, тоесть при обновлении таблицы lots, и последующим доставанием seller из seller, будет запрос к БД, который обратится по связи к таблице lots

2024-10-28 17:15 UTC, NikeTorchwood commented on AuctionTrading/Application/AuctionTrading.Application.Services/BidderApplicationService.cs
> +                    bidsRepository.UpdateAsync(bid, cancellationToken),
повторюсь очень тяжело осознать данный код:)
но смотри
Первое думаю что мы обходим все проверки которые, ты написала в других сервисах. Думаю если и дергать Update чего либо, то нужно делать не через репозиторий, а через сервис.
Здесь достаточно запутанно, так что просто теоретически точно не так выполняется. У нас есть связи и выглядит так что ты одни и те же действия делаешь несколько раз. Тоесть если например мы обновляем запись в customersRepository, мы же так же обновим и связанные таблицы. Аналогично с lots и bids, я думаю можно упростить.
так ну и непонятно, почему мы используем Update метод.
С точки зрения лота, это выглядит логично, но с точки зрения таблицы Bids я думаю это Add

2024-10-28 17:17 UTC, NikeTorchwood requested changes
ООООчень тяжелый сервис, ты сделала огромную работу - это отличный результат. Думаю справишься с решением проблем, апрувну когда будет работать:))))

2024-10-29 12:41 UTC, Yana-Kryukova commented on AuctionTrading/Domain/AuctionTrading.Domain.Repositories.Abstractions/IRepository.cs
> +    public interface IRepository<TEntity, in TId>
@NikeTorchwood если слушать лекцию otus, то интерфейсы репозиториев находятся именно в домене, для того, чтобы уровень инфраструктуры зависел от домена...

2024-11-04 16:50 UTC, closed without merging