Corrections made to the domain layer
IT-Siberians/AuctionTraidingMicroservice pull request #2
Opened 2024-08-29 17:14 UTC by Yana-Kryukova

2024-08-30 08:10 UTC, oleggolen requested changes
В целом всё уже гораздо лучше, чем было, но надо исправить всякие непонятные вещи, которые есть в данном коде, по сути только названия и одна серьёзная логическая ошибка

2024-08-30 08:10 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ArgumentNullOrWhiteSpaceException.cs
> +    }
Лучше здесь сделать базовым исключение ArgumentNullException, также лучше передавать названия параметра, так как ни из параметров исключения, ни из названия не следует никакого понимания о том, что вообще здесь null или пустая строка и куда смотреть

2024-08-30 08:10 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ArgumentNonPositiveException.cs
> +    }
Здесь лучше привязаться к конкретному типу деньги, который используется, также добавить конкретики где что и сколько

2024-08-30 08:10 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Exceptions/BidOnInactiveAuctionLotException.cs
> +    }
Можно добавить и ставку сюда

2024-08-30 08:10 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/DecimalValidator.cs
> +    public class DecimalValidator : IValidator<decimal>
Лучше опять же привязаться к типу деньги, используемом в объекте, чтобы было понятно что это такое

2024-08-30 08:10 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/DecimalValidator.cs
> +        }
Так как это decimal надо проверить на то, что если сумма 0.0000001 это тоже пройдёт, а не должно быть, так как у нас должно быть только 2 знака после запятой

2024-08-30 13:58 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/DecimalValidator.cs
> +        }
Может всё-таки ограничимся расчётами в рублях?
Тогда можно будет использовать целые числа

2024-08-31 16:53 UTC, Yana-Kryukova commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ArgumentNonPositiveException.cs
> +    }
@oleggolen Правильно ли я поняла, что здесь название не очень корректое и лучше сделать так
    internal class AmountNonPositiveException(string message, string paramName, decimal value)
        : ArgumentException(message, paramName)
    {
        public decimal Value => value;
    }

2024-08-31 17:48 UTC, closed without merging