Correction of the domain model
IT-Siberians/AuctionTraidingMicroservice pull request #6
Opened 2024-09-22 12:39 UTC by Yana-Kryukova

2024-09-24 12:52 UTC, Lietuonis commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ExceptionMessage.cs
> +        public const string USERNAME_NOT_NULL_OR_WHITE_SPACE = "The Title of auction lot mustn't be null, empty or consists only of white-space characters";
В тексте ошибки должно быть про UserName, а не Title

2024-09-24 23:10 UTC, m-a-ilnitsky requested changes
Есть ряд ошибок в логике и в именовании.
И лучше перед коммитом выполнять автоформатирование солюшена

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        public MoneyRub? RepurchasePrice { get; }
Может всё-таки лучше назвать FixedPrice или как-то ещё.
Сейчас из имени неочевидно, что это какая-то фиксированная ставка мгновенного выкупа

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (repurchasePrice != null && repurchasePrice < startPrice)
Сейчас получается что можно задать repurchasePrice == startPrice и тогда первая же ставка на аукционе сразу завершит торги.
В этом случае тогда вообще не будет аукциона

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            Status = status;
Если сравнения выполняются в UTC думаю имеет смысл все даты хранить в базе/сущностях сразу в UTC, а приведение выполнять в момент создания сущностей/записей базы

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        internal bool CancelLot(Seller seller)
Здесь слово лот в имени метода избыточно т.к. это и так метод класса лота

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        internal bool CompletedLot()
Здесь слово лот в имени метода избыточно т.к. это и так метод класса лота.
И имена таких методов обычно начинают с глагола is/has/и т.д.
Здесь мне кажется лучше назвать метод IsCompleted()

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new CompletedNotActiveAuctionLotException(this);
Здесь лучше не бросать исключение а возвращать, например, false.
По идее метод возвращающий bool используется как раз для всяких проверок чтобы не словить исключение, а здесь он сам может бросить исключение, значит перед тем как его дергать придется проверять какой-то еще метод, в общем это получается неудобно

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                || EndDate.ToUniversalTime() == DateTime.Now))
Справа видимо вместо DateTime.Now должно быть DateTime.UtcNow

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        internal bool CompletedLot()
Впрочем вначале неправильно понял смысл метода.
Т.к. этот метод не просто проверяет завершенность лота и возращает результат, а устанавливает статус Completed, то имя лучше задать другое.
Т.к. установка статуса Completed по смыслу важнее возвращаемого значения, этот метод лучше назвать SetCompleted() или SetStatusCompleted()

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (newBid.Lot != this)
Если сравнение выполняется по ссылке, то лучше использовать операторы is и is not, чтобы однозначно было понятно что сравниваются именно ссылки

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new BidOnInactiveAuctionLotException(this, newBid.Amount);
Не уверен, что в этом случае нужно бросать исключение (но это не точно, может и нужно).
Есть ощущение, возможно неверное, что в этом случае можно вернуть false.
Тут нужно смотреть в каких случаях эта ситуация может реализоваться.
Если это происходит только в случае ошибки логики, то исключение бросать правильно.
Если это может происходить в штатной ситуации (один пользователь добавляет ставку, а другой почти одновременно каким-то образом завершает лот) то вероятно лучше возвращать false, чтобы бэкэнд не падал на штатной ситуации

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                ? StartPrice + BidIncrement
Здесь точно нужно  "+ BidIncrement" ??
Я думаю что первый покупатель может поставить сумму равную самой стартовой цене StartPrice

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            return (newBid.Amount > minAmount && newBid.CreationTime.ToUniversalTime() < EndDate.ToUniversalTime());
newBid.Amount > minAmount - судя по логике вычисления minAmount, здесь должно быть >=

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Bid.cs
> +            : base(id)
Аргумент timestamp лучше в обоих конструкторах переименовать в соответствии с именем поля

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +        internal bool IsChangeUsername(Username newUsername)
IsChangeUsername - в текущем варианте правильнее будет писать IsChangedUsername.
Но по логике метода, здесь выполняемое изменение значения поля важнее возвращаемого методом значения.
Поэтому в метод правильнее назвать ChangeUsername, чтобы было видно что это сеттер, т.е. метод меняющий состояние объекта, а не просто метод проверки какого-то значения

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +            _observableAuctionLots.Append(lot);
Вместо Append от IEnumerable нужно использовать метод Add от ICollection.
Метод Append не изменит состояние коллекции от которой его вызовут, он лишь добавить элемент в возвращаемую последовательность, которая здесь никуда не сохраняется.
А метод Add добавляет элемент в саму коллекцию

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +                throw new BidOnInactiveAuctionLotException(lot, amount);
Возможно можно возвращать false.
Но это не точно, может текущий вариант и правильнее

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +            return lot.TryAddBid(newBid);
Наверняка добавление ставки не должно выполняться 2 раза (и второй раз результат по идее должен быть другой, хуже того, судя по логике в TryAddBid на второй раз он должен падать (правда там ошибка, поэтому не упадёт)).
Если это делается ради bool значения возвращаемого методом TryAddBid, то нужно просто сохранить значение в переменную при первом вызове

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +            Bid newBid = new Bid(this, lot, amount, DateTime.Now);
Здесь лучше сразу использовать UtcNow

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (!_bids.Contains(newBid))
Здесь не нужно отрицание, условие должно быть обратным

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Seller.cs
> +        internal bool IsChangeUsername(Username newUsername)
Здесь тоже важнее не возвращаемое значение, а выполняемое изменение состояния объекта.
Поэтому метод лучше назвать ChangeUsername.
И в целом, т.к. эта логика для продавца и покупателя общая её можно вынести в общий базовый класс

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Seller.cs
> +                ?? throw new AuctionLotDoesNotBelongToSellerException(this, lot);
Судя по всему здесь делается попытка проверки наличия лота у продавца.
Но сейчас это работает так:
_auctionLots.SingleOrDefault(lot) - этот метод возвращает любой первый элемент в коллекции _auctionLots, а если коллекция пуста, то он возвращает переданное значение по умолчанию, т.е. сам аргумент lot

Т.е.  проверка не работает, а если список лотов не пуст, то может отмениться вообще не тот лот.

Здесь вместо .SingleOrDefault(lot) лучше использовать метод .Any(e => e.Id == lot.Id), если без разницы от какого объекта (из аргумента или из коллекции) вызывать метод .CancelLot(this)
Если важно получить именно canceledLot из самой коллекции _auctionLots, то нужно использовать метод FirstOrDefault

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Exceptions/AnotherSellerCancelLotExeption.cs
> +        : InvalidOperationException($"The seller {seller.Username} can't cancel the {auctionLot.Title} auction lot.")
Здесь можно еще добавить в сообщение настоящего хозяина лота

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Exceptions/AuctionLotDoesNotBelongToSellerException.cs
> +        : InvalidOperationException($"The auction lot {lot.Title} is not in the seller's lot sequence (seller's id = {seller.Id}).")
Здесь тоже можно добавить в сообщение данные настоящего хозяина лота.
Но странно что в одном исключении в сообщении выводится seller.Username, а в другом seller.Id.
Думаю здесь тоже лучше выводить Username, т.к. оно уникально и лучше воспринимается человеком

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Exceptions/InvalidTimeStampBidException.cs
> +        public DateTime Timestamp => timestamp;
Здесь все имена (класса, аргумента, поля) переименовать в соответствии с новым именем поля CreationTime (вместо старого timestamp) у класса Bid

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            => other is not null && Equals(other as ValueObject<T>);
"other is not null &&" - эта часть не особо нужна, т.к. "other as ValueObject<T>" тоже может вернуть null и в итоге проверку на null все равно нужно будет выполнять в Equals(ValueObject<T>? other)
можно оставить только правую часть выражения

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            if ((object?)left == null || (object?)right == null)
Приведение к (object?) не нужно
И здесь вместо == лучше использовать is

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            return left.Equals(right);
Здесь достаточно просто вызвать статический Equals(left, right); и не делать отдельную ветку для нестатического метода Equals (статический метод сам его вызовет)

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ExceptionMessage.cs
> +    internal static class ExceptionMessage
Здесь лучше дать классу имя во множественном числе: ExceptionMessages

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/MoneyRUB.cs
> +        }
Методы лучше разделять пустой строкой.
И здесь код настолько короткий, что удобнее использовать стрелочный синтаксис

2024-09-24 23:10 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/MoneyAmountValidator.cs
> +        private bool IsValidAmount(decimal value)
Методы лучше разделять пустой строкой

2024-09-25 08:27 UTC, oleggolen requested changes
Всё стало сильно много лучше, осталось во всех местах доправить логику округления до двух знаков везде, согласовать переименованные свойства, и одну ошибку в логике исправить, и можно будет принять

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            Status = status;
Согласен полностью

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (repurchasePrice != null && repurchasePrice < startPrice)
Тут тоже согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        public MoneyRub? RepurchasePrice { get; }
Ну тут либо всё же составить словарь терминов, либо уже на выбор реализующих

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        internal bool CancelLot(Seller seller)
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        internal bool CompletedLot()
По первому согласен, по второму нет, так как статусы лота это больше техническая вещь, а здесь нужно использовать термины и глаголы из предметной области

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new CompletedNotActiveAuctionLotException(this);
А вот тут непонятно, имеет место как та, так и другая реализации, так как тут всё заависит от степени критичности ошибки и возможности продолжения работы приложения в целом, так как я понимаю в логике Яны, когда попытались завершить лот, по которому не начаты торги, это предельная критичекая ситуация, в принципе оно так и есть

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                || EndDate.ToUniversalTime() == DateTime.Now))
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new BidOnInactiveAuctionLotException(this, newBid.Amount);
Да согласен с аргументацией

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (newBid.Lot != this)
Ну тут мне кажется можно и так, хотя можно и перегрузить операторы для сравнения по Id или самому сравнивать Id чтобы наверняка

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (!_bids.Contains(newBid))
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                ? StartPrice + BidIncrement
По идее надо ставить больше стартовой цены

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            return (newBid.Amount > minAmount && newBid.CreationTime.ToUniversalTime() < EndDate.ToUniversalTime());
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Bid.cs
> +            : base(id)
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +        internal bool IsChangeUsername(Username newUsername)
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +            _observableAuctionLots.Append(lot);
Либо так, как описал Михаил, либо уже тогда писать _observableAuctionLots = _observableAuctionLots.Appen(lot); также коллекцию, я бы просто называл бы _lots

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +                throw new BidOnInactiveAuctionLotException(lot, amount);
Это обсдили в классе лота

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +            Bid newBid = new Bid(this, lot, amount, DateTime.Now);
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +            return lot.TryAddBid(newBid);
Тоже согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Seller.cs
> +        internal bool IsChangeUsername(Username newUsername)
Тоже согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Seller.cs
> +            if (Username == newUsername) return false;
Перенести на новую строку return

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Seller.cs
> +                ?? throw new AuctionLotDoesNotBelongToSellerException(this, lot);
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/MoneyRUB.cs
> +        }
Согласен полностью

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Description.cs
> +    public class Description(string description) : ValueObject<string>(new TitleValidator(), description)
Здесь должен быть DescriptionValidator

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/MoneyAmountValidator.cs
> +        private bool IsValidAmount(decimal value)
Тут лучше использовать математическое окугление, также как это проиходит в конструктор, и вообще работать только с числами с 2мя знаками после запятой

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ExceptionMessage.cs
> +    internal static class ExceptionMessage
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ExceptionMessage.cs
> +        public const string USERNAME_NOT_NULL_OR_WHITE_SPACE = "The Title of auction lot mustn't be null, empty or consists only of white-space characters";
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            if ((object?)left == null || (object?)right == null)
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            return left.Equals(right);
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            => other is not null && Equals(other as ValueObject<T>);
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Exceptions/AnotherSellerCancelLotExeption.cs
> +        : InvalidOperationException($"The seller {seller.Username} can't cancel the {auctionLot.Title} auction lot.")
Согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Exceptions/AuctionLotDoesNotBelongToSellerException.cs
> +        : InvalidOperationException($"The auction lot {lot.Title} is not in the seller's lot sequence (seller's id = {seller.Id}).")
Да согласен

2024-09-25 08:27 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain/Exceptions/InvalidTimeStampBidException.cs
> +        public DateTime Timestamp => timestamp;
Согласен

2024-09-25 14:58 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        internal bool CompletedLot()
Олег, расшифруйте что вы называете первым, а что вторым, мне не понятно, наверняка Яне тоже.
Но имена CompletedLot или IsCompleted точно не подходят, т.к. они не отражают основную логику метода

2024-09-25 20:52 UTC, Lietuonis commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        public MoneyRub? RepurchasePrice { get; }
Но ведь это буквальный перевод - "цена выкупа"

2024-09-25 23:58 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        public MoneyRub? RepurchasePrice { get; }
Но максимальная ставка по которой выкупили товар - это же тоже "цена выкупа".
Значит нужно более конкретное обозначение.
На мой взгляд

2024-09-27 06:18 UTC, Yana-Kryukova commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        public MoneyRub? RepurchasePrice { get; }
@m-a-ilnitsky я не считаю, что данное имя не корректное. В своем микросервисе я вообще не храню стоимость, по корой в итоге выкупили товар (У меня это просто последняя сделанная ставка в списке ставок).
Есть специальный термин из предметной области, который я взяла из финансового словаря англо-русского. 
Для меня FixedPrice - фиксированная цена ассоциируется с магазином, а не с аукционом! 
Поэтому я не буду использовать данное имя в своем микросервисе, а буду использовать имя из предметной области, т.е. RepurchasePrice, что обозначает цену выкупа!

2024-09-27 07:02 UTC, Yana-Kryukova commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (newBid.Lot != this)
@m-a-ilnitsky  is not не работает (ошибка компиляции CS9135	Ожидается значение константы типа "AuctionLot"	AuctionTrading.Domain). Не знаю кстати почему она здесь появилась...
Поэтому оставляю как есть.

2024-09-27 07:09 UTC, Yana-Kryukova commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                throw new BidOnInactiveAuctionLotException(this, newBid.Amount);
@oleggolen тут я наверное изменю логику.
Если лот отменен, то буду кидать исключение, потому что каким то образом фронт увидел отмененные лоты, а вот если лот завершен, то верну false. Потому что может быть так, что два человека делают ставку одновременно и один уже выкупил лот и у лота меняется статус на завершенный, тогда второй просто не успевает и в этом случае просто ставка не проходит.
Либо при установки ставки все таки можно кидать исключение и на фронте в зависимость от статуса выдавать что то вроде лот уже выкуплен или продавец отменил лот... как лучше?

2024-09-27 07:11 UTC, Yana-Kryukova commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                ? StartPrice + BidIncrement
@m-a-ilnitsky  я считаю, что все таки на торгах говорят, стартовая цена такая то, кто даст больше? поэтому реализовала именно так этот метод

2024-09-27 08:15 UTC, Yana-Kryukova commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/MoneyAmountValidator.cs
> +        private bool IsValidAmount(decimal value)
@oleggolen это же валидатор, мне кажется все таки не правильно выполнять здесь округление... Я получается при создании объекта типа деньги округляю до двух знаков и уже в конструктор передаю округленное число, а валидатор должен проверять что я не округлила допустим или я не права?

2024-09-27 08:20 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (newBid.Lot != this)
Сорри, да правильно, это и не должно работать.
Это я ерунду написал))
is и is not можно использовать только для сравнения с null или с конкретным типом.

2024-09-27 08:21 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                ? StartPrice + BidIncrement
Хм.. А в онлайн аукционах тоже такая логика?
Я то ни разу ими не пользовался

2024-09-27 08:55 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +        public MoneyRub? RepurchasePrice { get; }
@Yana-Kryukova  В табличке терминов есть русский термин "фиксированная ставка" (что можно перевести как FixedBid, хотя ранее вы это же имя использовали для шага ставки, которая сейчас называется BidIncrement).
И в той же табличке для этого термина есть английское слово Buyout, хотя наверное лучше BuyoutPrice. Кстати в википедии используется именно термин BuyoutPrice: https://en.wikipedia.org/wiki/Auction#Terminology
И в целом, когда выкупаем лот по фиксированной цене это как раз таки делается как в магазине))

Впрочем для меня без разницы BuyoutPrice или RepurchasePrice, т.к. перевод у них одинаковый "цена выкупа".
В обоих случаях я тогда для цены фактически выплаченной за лот буду вынужден использовать термин "цена молотка" т.е. HammerPrice

2024-09-27 09:04 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/MoneyAmountValidator.cs
> +        private bool IsValidAmount(decimal value)
Валидатор используется внутри конструктора,
Если предполагается, что в конструктор должны передать уже правильно округленное число, то такая проверка в валидаторе нужна. 
Если предполагается что округление должен выполнять сам конструктор, то делать соответствующую проверку в валидаторе нет смысла

2024-09-27 16:36 UTC, closed without merging