Fixed errors
IT-Siberians/AuctionTraidingMicroservice pull request #7
Opened 2024-09-27 16:37 UTC by Yana-Kryukova

2024-09-29 10:22 UTC, m-a-ilnitsky approved these changes
Есть мелкие некритичные претензии которые можно исправить позже или никогда.
Поэтому аппрув

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            return isCorrectBid == true ? BidStatus.Success : BidStatus.FaultedIncorrectBid;
bool-значение не нужно сравнивать с константой в условии, его принято использовать непосредственно или через отрицание.
Здесь вместо: return isCorrectBid == true ?
Лучше писать: return isCorrectBid ?

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            if (newBid.Lot != this)
Здесь если сравниваются именно ссылки то лучше использовать ReferenceEquals.
Честно говоря я сам в своей практике его почти не использовал, т.к. практически никогда не использовал перегрузку операторов, поэтому использование == и != было безопасным и однозначным.

Т.к. здесь у нас в коде куча перегруженных == и != то для сравнения ссылок лучше использовать ReferenceEquals,по крайней мере тогда по коду будет явно видно намерение сравнивать именно ссылки.
Сейчас глядя на код не очень понятно предполагается здесь сравнение по ссылке или по значению (чтобы понять это нужно смотреть реализована ли перегрузка операторов)

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +                && LastBid != null
Можно использовать is not

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/AuctionLot.cs
> +            MoneyRub minAmount = LastBid == null
Можно использовать is вместо ==, чтобы подчеркнуть что здесь сравнение выполняется по ссылке, а не по значению с помощью перегруженного оператора ==

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Customer.cs
> +            BidStatus isMakeBid = lot.MakeBid(newBid);
По имени isMakeBid кажется что это переменная типа bool, хотя это не так, т.е. имя вводит в заблуждение.
Если это статус ставки, то лучше так и назвать переменную

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Entities/Seller.cs
> +            return canceledLot.SetCancel(this);
По идее в именах CancelLot и SetCancel луше вместо слова Cancel использовать слово withdraw, которое используется здесь в комментарии.
Хотя мне оно тоже менее привычно чем Cancel

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain/Enums/LotStatus.cs
> +        Completed
А здесь не нужен еще статус не выкуплен?

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            return Value?.ToString() ?? GetType().ToString();
Вроде никогда не должно быть ситуации, что Value равно null.
В этом случае просто не должен создаваться ValueObject.
Поэтому лучше просто сделать: return Value!.ToString();
Пусть уж лучше упадёт, если вдруг возник null, тогда это позволит сразу выявить ошибку и исправить её

И здесь можно использовать стрелочный синтаксис

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            return Value!.GetHashCode();
Можно использовать стрелочный синтаксис

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +                return true;
Вторую и третью проверки лучше поменять местами, это будет эффективней

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +                return true;
И в if (other == null) лучше использовать is, чтобы было понятно что не используется перегруженный  оператор ==, а используется сравнение ссылок

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            return !(left == right);
Можно использовать стрелочный синтаксис

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Description.cs
> +    }
Т.к. у класса нет тела можно объявить его без фигурных скобок, закончив объявление точкой с запятой:
public class Description(string description) : ValueObject<string>(new TitleValidator(), description);

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ArgumentNullOrWhiteSpaceException.cs
> +    }
Т.к. у класса нет тела можно объявить его без фигурных скобок, закончив объявление точкой с запятой

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ValidatorNullException.cs
> +    }
Т.к. у класса нет тела можно объявить его без фигурных скобок, закончив объявление точкой с запятой

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/MoneyRUB.cs
> +
Лишняя пустая строка)))

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/UsernameValidator.cs
> +
Лишняя пустая строка

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/UsernameValidator.cs
> +        /// <summary>
Лучше добавить пустую строку

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/TitleValidator.cs
> +        /// <summary>
Лучше добавить пустую строку между объявлениями членов класса

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/MoneyAmountValidator.cs
> +        }
В текущем варианте эта проверка уже не нужна, т.к. конструктор сам округляет значение до этой проверки.
Обычно валидацию данных делают в публичных методах/конструкторах, т.к. там наибольшая вероятность получить невалидный аргумент, от пользователя класса, который не разобрался как его правильно использовать.
Здесь же валидируется значение полученное округлением в самом классе.
По идее разработчик класса должен брать на себя ответственность за то что логика внутри класса будет работать правильно (по крайней мере пока класс не начнут править).
Иначе разнообразные проверки можно вставлять практически после каждой операции и не будет критерия остановки добавления таких проверок

2024-09-29 10:22 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/MoneyRUB.cs
> +    public class MoneyRub(decimal amountInRub) : ValueObject<decimal>(
Не уверен, что в имени MoneyRub нужно указание на конкретную валюту.
По идее этот код будет работать также правильно и для долларов и для евро.
А если логика работы общая для разных валют, то нет причин искуственно сужать область применимости класса до одной конкретной валюты
Мне кажется лучше просто сократить имя до Money

2024-09-30 13:29 UTC, oleggolen requested changes
Немного повнимательнее тоит пиать код, чтобы не путать валидаторы и параметры, а так всё в целом хорошо, с некоторыми замечаниями Михаила согласен

2024-09-30 13:29 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/UserName.cs
> +    public class Username(string name) : ValueObject<string>(new TitleValidator(), name)
Тут скорее всего нужен UsernameValidator

2024-09-30 13:29 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/MoneyRUB.cs
> +    public class MoneyRub(decimal amountInRub) : ValueObject<decimal>(
Тут в целом согласен

2024-09-30 13:29 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/MoneyRUB.cs
> +            => new MoneyRub(m1.Value - m2.Value);
Можно сократить до просто new(m1.Value + m2.Value); И так со всеми остальными операциями. Тут ошибка,что нужно значение m2

2024-09-30 13:29 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Description.cs
> +    }
Здесь скорее имелся в виду DescriptionValidator

2024-09-30 13:29 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            return !(left == right);
Согласен

2024-09-30 13:29 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +                return true;
Согласен

2024-09-30 13:29 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Base/ValueObject.cs
> +            return Value!.GetHashCode();
Согласен

2024-09-30 13:29 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ArgumentNullOrWhiteSpaceException.cs
> +    }
Согласен

2024-09-30 13:29 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Exceptions/ValidatorNullException.cs
> +    }
Согласен

2024-09-30 13:29 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.ValueObjects/Validators/MoneyAmountValidator.cs
> +        }
Да тут согласен, обсудили на созвоне, пусть в принципе будет, но реально так

2024-10-04 11:49 UTC, Yana-Kryukova commented on AuctionTrading/Domain/AuctionTrading.Domain/Enums/LotStatus.cs
> +        Completed
@m-a-ilnitsky  Мой микросервис за этим не следит, не следит за тем как именно продан лот.

2024-10-04 12:10 UTC, closed without merging