Added IMemoryRepository
Added Application layer models and interfaces
IT-Siberians/AuctionTraidingMicroservice pull request #8
Opened 2024-09-30 10:28 UTC by Yana-Kryukova

2024-10-01 05:23 UTC, oleggolen requested changes
В целом достаточно хороший код, стоит дореализовать конфигурации, убрать лишние методы, и добавить недостающие, пока возвращаю, так как методами - грубая ошибка

2024-10-01 05:23 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/Base/IBidderCreateModel.cs
> +    public interface IBidderCreateModel<out TId> where TId : struct
Лучше для Id ещё добавить, что они сравнимые, то есть реализовать IEquitable

2024-10-01 05:23 UTC, oleggolen commented on AuctionTrading/Application/AuctionTrading.Application.Models/Base/ICreateModel.cs
> +namespace AuctionTrading.Application.Models.Base
Можно не писать эти неймспейсы в новом синтаксисе, также все эти using не нужны

2024-10-01 05:23 UTC, oleggolen commented on AuctionTrading/Infrastructures/Repositories.Implementations/InMemory/InMemorySellersRepository.cs
> +                   x => x.ActiveAuctionLots.FirstOrDefault(lot => lot.Id == auctionLotId) is not null));
Не очень понимаю смысл этого метода вообще. У лота есть продавец, и там сразу это понятно

2024-10-01 05:23 UTC, oleggolen commented on AuctionTrading/Infrastructures/Repositories.Implementations/EF/EfSellerRepository.cs
> +        }
Вообще убрать этот метод

2024-10-01 05:23 UTC, oleggolen commented on AuctionTrading/Domain/AuctionTrading.Domain.Repositories.Abstractions/ISellersRepository.cs
> +        Task<Seller?> GetSellerByAuctionLotIdAsync(Guid auctionLotId);
Убрать совершенно лишний метод везде

2024-10-04 15:17 UTC, closed without merging

2024-10-11 19:26 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain.Repositories.Abstractions/IRepository.cs
> +    public interface IRepository<TEntity, in TId> where TEntity : Entity<TId> where TId : struct
Для TId лучше добавить ограничение IEquatable

2024-10-11 19:26 UTC, m-a-ilnitsky commented on AuctionTrading/Domain/AuctionTrading.Domain.Repositories.Abstractions/IRepository.cs
> +    public interface IRepository<TEntity, in TId> where TEntity : Entity<TId> where TId : struct
Несколько where лучше писать столбиком - каждый where с новой строки.
Тогда ограничения будут лучше читаться

2024-10-11 19:26 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructures/Repositories.Implementations/EF/EfAuctionLotRepository.cs
> +            .FirstOrDefaultAsync(l => l.Id == id);
Лучше никогда не использовать в коде однобуквенное имя "малое эл" (l).
Во многих шрифтах оно похоже на "большое И" или на "единицу".
Это может привести к трудно обнаруживаемым ошибкам.
Здесь лямбда очень короткая и вроде не страшно, но лучше не рисковать.
В общем случае в лямбде можно писать например "e" (сокращение от "element" подходит на все случаи жизни)

2024-10-11 19:26 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructures/Repositories.Implementations/EF/EfCustomerRepository.cs
> +                                                                .FirstOrDefaultAsync(s => s.Username.Value == username);
Лучше каждый вызов в цепочек вызовов писать с новой строки.
Тогда будет лучше виден используемый Include

2024-10-11 19:26 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructures/Repositories.Implementations/EF/EfRepository.cs
> +                                                                        where TEntity : Entity<TId> where TId : struct
лучше каждый where писать с новой строки, это улучшит восприятие ограничений

2024-10-11 19:26 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructures/Repositories.Implementations/EF/EfSellerRepository.cs
> +        public override Task<Seller?> GetByIdAsync(Guid id) => _sellers.Include(s => s.ActiveAuctionLots)
Лучше Include написать с новой строки, чтобы его было лучше видно.
Цепочки вызовов лучше выводить в один столбец, чтобы вся их логика лучше считывалась человеком

2024-10-11 19:26 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructures/Repositories.Implementations/EF/EfSellerRepository.cs
> +        public Task<Seller?> GetSellerByUsernameAsync(string username) => _sellers.Include(s => s.ActiveAuctionLots)
Аналогично про цепочки вызовов в столбец

2024-10-11 19:26 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructures/Repositories.Implementations/InMemory/InMemoryRepository.cs
> +    public class InMemoryRepository<TEntity, TId>(IEnumerable<TEntity> entities) : IRepository<TEntity, TId> where TEntity : Entity<TId> where TId : struct
Лучше каждый where написать с новой строки.
Когда where несколько в одной строке это плохо читается

2024-10-11 19:26 UTC, m-a-ilnitsky commented on AuctionTrading/Infrastructures/Repositories.Implementations/InMemory/InMemoryRepository.cs
> +    public class InMemoryRepository<TEntity, TId>(IEnumerable<TEntity> entities) : IRepository<TEntity, TId> where TEntity : Entity<TId> where TId : struct
И лучше добавить ограничение IEquatable для TId